myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home_page_view, register_page_view, login_page_view, logout_page_view, search_results_view

urlpatterns = [
    path('', home_page_view, name='home_page_view'),
    path('register/', register_page_view, name='register_page_view'),
    path('login/', login_page_view, name='login_page_view'),
    path('logout/', logout_page_view, name='logout_page_view'),
    path('search/', search_results_view, name='search_results_view'),
    path('admin/', admin.site.urls),
    path('pipelines/', include('pipelines.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    #path('', include('mainapp.urls')),
]

pipelines/urls.py
from django.urls import path
from .views import pipeline_list_view, pipeline_detail_view, pipeline_execute_view

app_name = 'pipelines'
urlpatterns = [
    path('', pipeline_list_view, name='pipeline_list_view'),
    path('<int:id>/', pipeline_detail_view, name='pipeline_detail_view'),
    path('<int:id>/execute/', pipeline_execute_view, name='pipeline_execute_view'),
]

app/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models

# Create your models here.

pipelines/models.py
from django.db import models

class Pipeline(models.Model):
	title = models.CharField(max_length=20)
	inputs = models.CharField(default="", max_length=150)
	outputs = models.CharField(default="", max_length=150)
	algorithms = models.CharField(default="", max_length=200)

pages/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User 
		fields = ['username', 'email', 'password1', 'password2']

app/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
#from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
#from datasets.models import Dataset
from django.core.paginator import Paginator

# Create your views here.
from .models import *
from .forms import CreateUserForm

def home_page_view(request, *args, **kwargs):
	return render(request, "home.html", {})

'''def my_data_view(request, *args, **kwargs):
	datasets = Dataset.objects.all()
	context = {
		"datasets": datasets
	}
	return render(request, "mydata.html", context)

def my_datasets_view(request, *args, **kwargs):
	datasets = Dataset.objects.all()
	paginated_datasets = Paginator(datasets, 3)
	page_number = request.GET.get('page', 1)
	page = paginated_datasets.get_page(page_number)
	if page.has_next():
		next_url = f'?page={page.next_page_number()}'
	else:
		next_url = ''
	if page.has_previous():
		prev_url = f'?page={page.previous_page_number()}'
	else:
		prev_url = ''
	context = {
		"datasets": page,
		"next_page_url": next_url,
		"prev_page_url": prev_url
	}
	return render(request, "mydatasets.html", context)'''

def search_results_view(request):
	search_query = request.GET.get('search', '')
	context = {}
	'''if search_query:
		datasets = Dataset.objects.filter(title__icontains=search_query)
		paginated_datasets = Paginator(datasets, 5)
		page_number = request.GET.get('page', 1)
		page = paginated_datasets.get_page(page_number)
		if page.has_next():
			next_url = f'?page={page.next_page_number()}'
		else:
			next_url = ''
		if page.has_previous():
			prev_url = f'?page={page.previous_page_number()}'
		else:
			prev_url = ''
		context['datasets'] = page
		context['search_query'] = search_query'''
	return render(request, "search_results.html", context)

def register_page_view(request, *args, **kwargs):
	form = CreateUserForm()
	if request.method == "POST":
		form = CreateUserForm(request.POST)
		if form.is_valid():
			form.save()
			user = form.cleaned_data.get('username')
			messages.success(request, 'Account was created for ' + user)
			return redirect(login_page_view)
	context = {
		"form": form
	}
	return render(request, "register.html", context)

def login_page_view(request, *args, **kwargs):
	context = {}
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(request, username=username, password=password)

		if user is not None:
			login(request, user)
			return redirect(home_page_view)
		else:
			messages.info(request, 'Username OR password is incorrect.')
	return render(request, "login.html", context)

def logout_page_view(request, *args, **kwargs):
	logout(request)
	return redirect(home_page_view)

pipelines/views.py
# Django-related imports
from django.shortcuts import render
from .models import Pipeline
#from .tasks import sleeping
from queue import Queue

# Processor-related imports
import base64, struct, xml.etree.ElementTree as ET
import os.path
import subprocess
import json
from pathlib import Path
#from bs4 import BeautifulSoup as bs
from django.core.files import File
from django.conf import settings
from .thread import CreatePipelineTasks
from django.http import JsonResponse
from django.views.generic import View

#global queue

# Create your views here.
def pipeline_list_view(request):
    queryset = Pipeline.objects.all() # List of pipelines
    context = {
        "object_list": queryset
    }
    return render(request, "pipelines/pipeline_list.html", context)

def pipeline_detail_view(request, id):
    obj = Pipeline.objects.get(id=id)
    input_files = {}
    if request.method == "POST":
        input_files['sample_data'] = request.FILES["SampleDataFile"]
    context = {
        "object": obj,
        "inputs": obj.inputs.split("|"),
        "input_files": input_files
    }
    print("And now...")
    print(context)
    return render(request, "pipelines/pipeline_detail.html", context)

def pipeline_execute_view(request, id):
    print("In execution")
    print(request)
    print(request.FILES)
    print("And the pipeline is...")
    context = {}
    obj = Pipeline.objects.get(id=id)
    print(obj)
    context["object"] = obj
    inputs = {}
    execution_map = {}
    queue = Queue()
    print("Is it in?")
    if request.method == "POST":
        context['pipeline_title'] = obj.title
        inputs['sample_data'] = request.FILES["SampleDataFile"]
        print(inputs['sample_data'])
        inputs['spec_lib'] = request.POST.get("SpecLibFile", None)
        inputs['iRTs'] = request.POST.get("iRTsFile", None)
        context["sample_data"] = inputs['sample_data']
        context["spec_lib"] = inputs['spec_lib']
        context["iRTs"] = inputs['iRTs']
        context["algorithms"] = obj.algorithms.split(",")
        tasks = []
        algorithms_to_task_ids = {}
        print("About to create pipeline tasks...")
        print(obj)
        print(obj.algorithms)
        CreatePipelineTasks(obj.title, obj.algorithms, inputs, queue).start()
        print("Done creating pipeline tasks...")
        print(queue)
        algorithm_size = len(obj.algorithms.split(","))
        while True:
            print("In while...")
            flag = not (queue.qsize() == algorithm_size)
            if flag:
                pass
            else:
                print("In else statement")
                algorithm_to_executable = {"SpectralExtraction": "SpectralExtraction.exe", "DeNovo": "DeNovoSequencingAlgorithm.exe", "Database": "DatabaseSearchAlgorithm.exe"}#, "FDR": "FDR.exe"}
                algorithms_to_task_ids = queue.get()
                print(algorithms_to_task_ids)
                print(context["algorithms"])
                for algorithm in context["algorithms"]:
                    context['task_id_'+algorithm] = algorithms_to_task_ids[algorithm_to_executable[algorithm]]
                break
        count = 0
    print(algorithms_to_task_ids)
    print(context)
    return render(request, "pipelines/pipeline_execute.html", context)

def create_execution_map(algorithms):
    new_map = {}
    current_val = list(algorithms)[0]
    new_map[current_val] = "Waiting..."
    if isinstance(algorithms[current_val], str):
        temp_map = new_map.update({algorithms[current_val]: "Waiting..."})
    else:
        new_map.update(create_execution_map(algorithms[current_val]))
    return new_map

pages/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!-- Home section starts -->
<section id="home" class="home">
	<div class="col-md-2"></div>
	<div class="col-md-8 contains-search">
		<h1 class="banner">Find everything you need here!</p>
	</div>
	<div class="col-md-2"></div>
	</div>
	<div class="row">
		<form action="{% url 'search_results_view' %}">
			<input type="search" name="search" placeholder="Search for biological data..." style="width: 340px; border-radius: 12px 0 0 12px;" class="form-control search-box">
			<div class="dropdown">
				<button class="btn btn-secondary dropdown-toggle search-for-button" type="button" style="width: 140px; height: 34px; font-size: 16px; margin-top: 0px; border-radius: 0 12px 12px 0;" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Search for...      <span class="caret"></span>
				</button>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="border-radius: 0; width: 26px;">
					<a class="dropdown-item" href="#">Datasets</a>
					<a class="dropdown-item" href="#">Experiments</a>
					<a class="dropdown-item" href="#">Peptides/Proteins</a>
				</div>
			</div>
		</form>
	</div>
	<div class="row">
		<button class="btn btn-primary" type="submit" style="width: 160px; height: 34px; font-size: 15px; float: left; margin: 7px; margin-top: 10px;">Fibonacci Search!</button>
		<button class="btn btn-secondary" type="button" style="width: 160px; height: 34px; font-size: 15px; float: left; margin: 7px; margin-top: 10px;">
			Advanced Search
		</button>
	</div>
    <div class="wave wave1"></div>
    <div class="wave wave2"></div>
    <div class="wave wave3"></div>

    <div class="fas fa-cog nut1"></div>
    <div class="fas fa-cog nut2"></div>
</section>
<!-- Home section ends -->
<section id="about" class="about">
	<h1 class="heading">about us</h1>
	<div class="row">
		<div class="content">
			<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
				<p>Hello, world! Welcome to Fibonacci, where we have all kinds of omics, sequencing and imaging pipelines which you can dynamically 'glue together' into a larger workflow and automate all of your processes! If you are a life scientist with no skills in mathematics and/or programming, this is the right place for you! If you are not that, it is still not unlikely that this is the right place for you! Get started now (or at a later time of your convenience)! :D</p>
			</div>
			<div class="col-md-2"></div>
		</div>
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<a href="#"><button class="btn">Read More</button></a>
		</div>
		</div>
		<div class="image">
			<img src="{% static 'img/dna.jpg' %}" alt="" width="500px">
		</div>
	</div>
</section>
<!--<section id="service" class="service">
        <h1 class="heading">Our Services</h1>
        <div class="row">
            <div class="image">
                <img src="{% static 'img/img1.png' %}" alt="" width="900px">
            </div>
            <div class="content">
                <h3>We provide cool services such as:</h3>
                <p>Lorem ipsum dolor sit amet.</p>
                <a href="#"><button class="btn">Read More</button>
            </div>
        </div>
        <div class="row">
            <div class="content">
                <h3>Mobile Friendly</h3>
                <p>Lorem ipsum dolor sit amet.</p>
                <a href="#"><button class="btn">Read More</button>
            </div>
            <div class="image">
                <img src="{% static 'img/img2.png' %}" alt="" width="900px">
            </div>
        </div>
        <div class="row">
            <div class="image">
                <img src="{% static 'img/img1.png' %}" alt="" width="900px">
            </div>
            <div class="content">
                <h3>Responsive Design</h3>
                <p>Lorem ipsum dolor sit amet.</p>
                <a href="#"><button class="btn">Read More</button>
            </div>
        </div>
        <div class="row">
            <div class="content">
                <h3>Web Hosting</h3>
                <p>Lorem ipsum dolor sit amet.</p>
                <a href="#"><button class="btn">Read More</button>
            </div>
            <div class="image">
                <img src="{% static 'img/img2.png' %}" alt="" width="900px">
            </div>
        </div>
    </section>->
    <!-- Service section ends -->
    <!-- Team section starts -->
    <!--<section id="team" class="team">
        <h1 class="heading">Our Team</h1>
        <div class="row">
            <div class="card">
                <div class="image">
                    <img src="{% static 'img/img1.png' %}" alt="" width="900px">
                </div>
                <div class="info">
                    <h3>Someone's Name</h3>
                    <span>Web Designer</span>
                    <div class="icons">
                        <a href="#" class="fab fa-facebook-f"></a>
                        <a href="#" class="fab fa-twitter"></a>
                        <a href="#" class="fab fa-instagram"></a>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="image">
                    <img src="{% static 'img/img2.png' %}" alt="" width="900px">
                </div>
                <div class="info">
                    <h3>Someone's Name</h3>
                    <span>Web Designer</span>
                    <div class="icons">
                        <a href="#" class="fab fa-facebook-f"></a>
                        <a href="#" class="fab fa-twitter"></a>
                        <a href="#" class="fab fa-instagram"></a>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="image">
                    <img src="{% static 'img/img1.png' %}" alt="" width="900px">
                </div>
                <div class="info">
                    <h3>Someone's Name</h3>
                    <span>Web Designer</span>
                    <div class="icons">
                        <a href="#" class="fab fa-facebook-f"></a>
                        <a href="#" class="fab fa-twitter"></a>
                        <a href="#" class="fab fa-instagram"></a>
                    </div>
                </div>
            </div>
        </div>
    </section>-->
    <!-- Team section ends -->
    <!-- Contact section starts -->
    <!--<section id="contact" class="contact">
        <h1 class="heading">Contact Us</h1>
        <div class="row">
            <div class="image">
                <img src="{% static 'img/img1.png' %}" alt="" width="500px">
            </div>
            <div class="form-container">
                <form action="">
                    <div class="inputBox">
                        <input type="text" placeholder="first name">
                        <input type="text"
                        placeholder="last name">
                    </div>
                    <input type="email" placeholder="email">
                    <textarea name="" id="" cols="30" rows="10" placeholder="message"></textarea>
                    <input type="submit" value="send">
                </form>
            </div>
        </div>
    </section>-->
    <!-- Contact section ends -->
    <!-- FAQ section starts -->
    <!--<section id="faq" class="faq">
        <h1 class="heading">FAQ</h1>
        <div class="row">
            <div class="image">
                <img src="{% static 'img/img1.png' %}" alt="" width="500px">
            </div>
            <div class="accordion-container">
                <div class="accordion">
                    <div class="accordion-header">
                        <span>+</span>
                        <h3>How much will it cost?</h3>
                    </div>
                    <div class="accordion-body">
                        <p>Lorem ipsum dolor sit amet.</p>
                    </div>
                </div>

                <div class="accordion">
                    <div class="accordion-header">
                        <span>+</span>
                        <h3>How to update website?</h3>
                    </div>
                    <div class="accordion-body">
                        <p>Lorem ipsum dolor sit amet.</p>
                    </div>
                </div>

                <div class="accordion">
                    <div class="accordion-header">
                        <span>+</span>
                        <h3>Is the provided domain free?</h3>
                    </div>
                    <div class="accordion-body">
                        <p>Lorem ipsum dolor sit amet.</p>
                    </div>
                </div>

                <div class="accordion">
                    <div class="accordion-header">
                        <span>+</span>
                        <h3>Is it SEO friendly?</h3>
                    </div>
                    <div class="accordion-body">
                        <p>Lorem ipsum dolor sit amet.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>-->
    <!-- FAQ section ends -->
{% endblock %}

pages/templates/mydata.html
{% extends 'base.html' %}


{% block content %}

<div class="row data-container">
	<div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
	<div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-xs-4 datasets">
		<h1>My Datasets</h1>
		{% for dataset in datasets %}
			{{ dataset.title }}
		{% endfor %}
		<button type="submit" class="btn btn-primary"><a href="{% url 'my_datasets_view' %}">See All Datasets</a></button>
	</div>
	<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
	<div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-xs-4 experiment-results">
		<h1>My Experiment Results</h1>
		Experiment Result 1
		Experiment Result 2
		Experiment Result 3
	</div>
	<div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
</div>

{% endblock %}

pages/templates/mydatasets.html
{% extends 'base.html' %}

{% block content %}

{% for dataset in datasets.object_list %}
<div class="row data-container">
	<div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
	<div class="col-xl-10 col-lg-10 col-md-10 col-sm-10 col-xs-10 dataset-detail">
		{{ dataset.title }},
		Private: {{ dataset.private }}
	</div>
	<div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
</div>
{% endfor %}
<nav aria-label="...">
  <ul class="pagination">
    <li class="page-item {% if not prev_page_url %} disabled {% endif %}">
      <a class="page-link" href="{{ prev_page_url }}" tabindex="-1">Previous</a>
    </li>
    {% for n in datasets.paginator.page_range %}
    	{% if datasets.number == n %}
	    	<li class="page-item">
	    		<a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only">(current)</span></a>
	    	</li>
    	{% elif n > datasets.number|add:-3 and n < datasets.number|add:3 %}
				<li class="page-item">
    			<a class="page-link" href="?page={{ n }}">{{ n }}</a>
    		</li>
    	{% endif %}
    {% endfor %}
    	<li class="page-item {% if not next_page_url %} disabled {% endif %}">
      	<a class="page-link" href="{{ next_page_url }}">Next</a>
    	</li>
  </ul>
</nav>

{% endblock %}

pipelines/templates/pipelines/pipeline_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<section id="pipelines-views" class="pipelines-views">
<div class="pipeline-construction single-pipeline-container">
<form method="POST" action="{% url 'pipelines:pipeline_execute_view' object.id %}" enctype="multipart/form-data">
<div class="row">
	<div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
	<div class="form-container col-xl-10 col-lg-10 col-md-10 col-sm-10 col-xs-10">
		<p>{{ object.title }} Pipeline!</p>
		<h3>Set Pipeline Parameters Below!</h3>
		    <div class="inputBox">
		    	<label style="width:20%">Run Name:</label>
		        <input style="width:75%" type="text" placeholder="Execution Name...">
		    </div>
		    <div class="inputBox">
		    	<label style="width:20%">Output Folder:</label>
		        <input style="width:75%" type="text" placeholder="Output Folder...">
		    </div>
	</div>
	<div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
</div>
<div class="row pipeline-file-selection">
	<div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
	{% csrf_token %}
	{% for input in inputs %}
		{% ifequal input "SampleData" %}
		<div class="form-container col-xl-3 col-lg-3 col-md-3 col-sm-3 col-xs-3">
			<input type="file" name="SampleDataFile" id="real-sample-data-file" style="display: none;" accept=".mzML, .RAW" required />
			<button type="button" id="custom-sample-data-button">Add Mass Spec Run</button>
			<br/>
			<br/>
			<select id="sample_data_list" name="sample_data_list" size="5" multiple>
				<option> </option>
			</select>
			<table class="table table-bordered" id="sample_data_files">
			</table>
			<!--<input class="upload-box" type="file" name="SampleDataFile" id="sample-data-file" required>-->
		</div>
		{% endifequal %}
		{% ifequal input "SpectralLibrary" %}
		<div class="form-container col-xl-3 col-lg-3 col-md-3 col-sm-3 col-xs-3">
			<input type="file" name="SpecLibFile" id="real-spec-lib-file" style="display: none;" accept=".mzML" />
			<button type="button" id="custom-spec-lib-button">Add Spectral Library</button>
			<br/>
			<br/>
			<select name="spec_lib_list" id="spec_lib_list" size="5" multiple>
				<option> </option>
			</select>
			<table class="table table-bordered" id="spec_lib_files">
			</table>
		</div>
		{% endifequal %}
		{% ifequal input "iRTs" %}
		<div class="form-container col-xl-3 col-lg-3 col-md-3 col-sm-3 col-xs-3">
			<input type="file" name="iRTsFile" id="real-irts-file" style="display: none;" accept=".pqp" />
			<button type="button" id="custom-irts-button">Add iRT Library</button>
			<br/>
			<br/>
			<select name="irts_list" id="irts_list" size="5" multiple>
				<option> </option>
			</select>
			<table class="table table-bordered" id="irt_files">
			</table>
		</div>
		{% endifequal %}
	{% endfor %}
	<div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
</div>
<div class="row">
	<div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
	<div class="col-xl-10 col-lg-10 col-md-10 col-sm-10 col-xs-10">
		<button class="btn btn-primary" type="submit">Run Pipeline!</button>
	</div>
	<div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
</div>
</form>
</div>
</section>
<script src="{% static 'js/pipeline-construction.js' %}" defer></script>

{% endblock %}

pipelines/templates/pipelines/pipeline_list.html
{% extends 'base.html' %}

{% block content %}
<section id="pipelines" class="pipelines">
<div class="row pipeline-header">
    <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
    <div class="col-xl-10 col-lg-10 col-md-10 col-sm-10 col-xs-10 pipeline-list">
    <h1>Pipelines</h1>

    <p>Just below we have a list of your active pipelines followed by a list of pipelines to activate. You can submit data into the pipelines and when the active pipeline has completed the results will be accessible <a href="#">here</a> or in the "My Data" link in the navigation bar above. You can also connect pipelines into a larger workflow by clicking <a href="#">here</a> where we can join pipelines into a larger workflow (or in the "My Flows" link in the navigation bar above).</p> 

    </div>
    <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
</div>
<div class="row active-pipeline-collection">
    <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
    <div class="col-xl-10 col-lg-10 col-md-10 col-sm-10 col-xs-10 pipeline-list">
    <h1>Active Pipelines</h1>

    <p>You currently have no active pipelines.</p> 

    </div>
    <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
</div>
<div class="pipeline-collection">
{% for pipeline in object_list %}
    {% if forloop.counter0|divisibleby:"2" %}
    <div class="row pipelines">
        <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
    {% endif %}
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-xs-4 pipeline-container">
        <a href="{% url 'pipelines:pipeline_detail_view' pipeline.id %}">{{ pipeline.title }}</a>
        <p>Description: This is a pipeline!</p>
    </div>
    {% if forloop.counter|divisibleby:"2" %}
    <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
    </div>
    {% else %}
    <div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
    {% endif %}
{% endfor %}
{% if not object_list|length|divisibleby:"2" %}
</div>
</div>
</section>
{% endif %}
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/script.js' %}" defer></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>


    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abel">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css" rel="stylesheet">

    <style>
        .brand-title a { 
            color: black;
            font-family: "Abel";
        } /* CSS link color */
    </style>

    <title>Fibonacci - Integrated Biotech</title>
  </head>
  <body onresize="{% if 'pipelines' in request.path and 'execute' in request.path %}resize_graph(){% endif %}" onload="{% if 'pipelines' in request.path and 'execute' in request.path %}load_pipeline_tree(true){% endif %}">
    <!-- Header section starts -->
    <header class="header">
        <a href="{% url 'home_page_view' %}" class="fibonacci">fibonacci</a>
        <div class="fas fa-bars"></div>
        <nav class="navbar">
            <ul class="nav-items">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'pipelines:pipeline_list_view' %}">Pipelines</a></li>
                    <li><a href="{% url 'logout_page_view' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login_page_view' %}">Login</a></li>
                    <li><a href="{% url 'register_page_view' %}">Register</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <!-- Header section ends -->
    {% block content %}
        Replace me!
    {% endblock %}
    <!-- Footer section starts -->
    <section class="footer">
        <h1 class="footer-text">Created by the Fibonacci team | All rights reserved.</h1>
        <div class="icons">
            <a href="#" class="fab fa-facebook-f"></a>
            <a href="#" class="fab fa-twitter"></a>
            <a href="#" class="fab fa-instagram"></a>
        </div>
    </section>
    <!-- Footer section ends -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </body>
</html>